### ISSUE TITLE
Single quotes around suggestion and question mark

### ISSUE THREAD

**Issue by xyclonei** [SylvainDe/DidYouMean-Python#10]
Hi! I am a great fan of the work you're doing here.

For the sake of pedantry, would it be possible to add a question mark at the end of the error message and single quotation marks around the suggestion, like say, *NameError: global name 'maxi' is not defined. Did you mean 'max'?*

Cheers!

**Comment by SylvainDe** [comment]
Hey!
Thanks for the message! It seems like the suggested format is better indeed
and I should be able to change that easily in the next couple of days.
Cheers

**Comment by SylvainDe** [comment]
As an additional note to myself: range
Readme is to be updated too (and obviously code and tests are to be updated too)
