### ISSUE TITLE
`Maximum recursion depth exceeded` on Pypy

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/DidYouMean-Python#22]
I have the following error:

```
======================================================================
ERROR: test_unbound_global (didyoumean_sugg_tests.UnboundLocalErrorTests)
Should be global nb.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_sugg_tests.py", line 700, in test_unbound_global
    self.throws(bad_code, UNBOUNDLOCAL)
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_sugg_tests.py", line 302, in throws
    get_suggestions_for_exception(value, traceback))
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_internal.py", line 302, in suggest_name_as_name_typo
    for name in get_close_matches(name, objdict.keys()):
  File "/home/travis/build/SylvainDe/DidYouMean-Python/didyoumean/didyoumean_internal.py", line 78, in get_close_matches
    for w in difflib.get_close_matches(word, possibilities, 3, 0.7)
  File "/opt/python/pypy-5.3.1/lib-python/2.7/difflib.py", line 738, in get_close_matches
    s.set_seq1(x)
  File "/opt/python/pypy-5.3.1/lib-python/2.7/difflib.py", line 256, in set_seq1
    self.a = a
RuntimeError: maximum recursion depth exceeded
```

when running the unit test on Travis. It does not seem related to the new changes performed.

This seems to affect:

```
$ python --version
Python 2.7.10 (7e8df3df9641, Jun 14 2016, 13:58:02)
[PyPy 5.3.1 with GCC 4.8.2]

$ python --version
Python 2.7.10 (7e8df3df9641, Jun 14 2016, 13:58:02)
[PyPy 5.3.1 with GCC 4.8.2]

```
but not:

```
$ python --version
Python 3.2.5 (b2091e973da6, Oct 19 2014, 18:29:55)
[PyPy 2.4.0 with GCC 4.6.3]
```

Looking for "pypy maximum recursion depth exceeded travis" in Google shows other similar looking errors. To be investigated.

**Comment by TiberiumPY** [comment]
@SylvainDe on PyPy 5.6 this works for me (no recursion error)

**Comment by TiberiumPY** [comment]
@SylvainDe you can use PyPy 5.6 on travis

**Comment by SylvainDe** [comment]
Hello @TiberiumPY , I have no idea how you stumbled open this issue but many thanks for your input :-D. I'll give it a try asap (do you reckon I should use `pypy-5.6` as a Python version). In any case, I do not quite understand why this used to work but doesn't anymore...

**Comment by TiberiumPY** [comment]
@SylvainDe can you give example code which raises an error on PyPy 5.3 ?
(yeah, I ran tests and everything is fine, just to be 100% sure)

**Comment by SylvainDe** [comment]
@TiberiumPY I haven't run the tests locally yet. However, I had setup the continuous integration on Travis to run on as many platforms as possible as my code relies on parts that are likely to fail from one implementation to another ("parsing" of error messages, code introspection, etc).

In any case, the failure can be observed on the job logs on https://travis-ci.org/SylvainDe/DidYouMean-Python .
For instance:
 - https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/187322379 (job 477.12
 - https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/187322381 (job 477.14)
It started failing on build 470 ( https://travis-ci.org/SylvainDe/DidYouMean-Python/builds/187253650 ) ; build 469 was just fine ( https://travis-ci.org/SylvainDe/DidYouMean-Python/builds/187244055 ) even though the commit introduced with build 470 ( https://github.com/SylvainDe/DidYouMean-Python/commit/bcf9fa667110f745102b59aa37c18ac6c430ddf1 ) has nothing to do with the issue.
I have yet to check the logs to understand the difference in what happened.

**Comment by SylvainDe** [comment]
For the record, I had a similar issue a few days ago and restarting the job did fix it. I haven't managed to find the logs for that run/re-run yet.

**Comment by SylvainDe** [comment]
This is driving me crazy. Removing passing test cases makes the issue disappear...

**Comment by TiberiumPY** [comment]
@SylvainDe why are you doing this? PyPy 5.3 is an old version

**Comment by SylvainDe** [comment]
@TiberiumPY To be fair, I do know much about the different PyPy versions. I've just set up my travis.yml file ( https://github.com/SylvainDe/DidYouMean-Python/blob/master/.travis.yml ) to run on all the versions I've found on https://docs.travis-ci.com/user/languages/python/ because I didn't know better...
At the moment, I've changed the config to allow failures on the PyPy configs but I'd like to understand what's going on (and fix it and/or open an issue in the relevant project).

**Comment by SylvainDe** [comment]
I've tried (unsuccessfully) to add PyPy 5.6 in the Travis config :(

**Comment by TiberiumPY** [comment]
@SylvainDe you need to add manual config for latest pypy

**Comment by TiberiumPY** [comment]
@SylvainDe or use this:
https://github.com/frol/flask-restplus-server-example/blob/master/.travis.yml

just change 5.4.1 with 5.6.0

**Comment by SylvainDe** [comment]
@TiberiumPY Thank you so much, I'll try this asap :-)

**Comment by TiberiumPY** [comment]
@SylvainDe https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/187717214

no recursion error anymore (seems just PyPy guys raised max depth from 100 to 1000)

**Comment by SylvainDe** [comment]
Indeed, thanks for your help!
(It is surprising that adding/removing unrelated successful tests affects how deep we go into the calls)

**Comment by TiberiumPY** [comment]
@SylvainDe tests pass!
BTW, maybe you can remove PyPy from allowed failures?

**Comment by TiberiumPY** [comment]
@SylvainDe and remove PyPy -5 3.1 completely

**Comment by SylvainDe** [comment]
@TiberiumPY Sure, will do!
Btw, do you know if using the same technique I'd be able to run on multiple version of PyPy? The fact that changing from one version to another was useful to detect a new issue (cf https://github.com/SylvainDe/DidYouMean-Python/commit/2c040f9268a9feff249b263219bd005ecf14bc8f ) proves that it'd probably help me to run the code on most versions of PyPy released.

**Comment by TiberiumPY** [comment]
@SylvainDe probably - yes
This script uses "pyenv", so you can use all versions supported by pyenv

**Comment by TiberiumPY** [comment]
@SylvainDe these are all pypy versions supported by pyenv

**Comment by SylvainDe** [comment]
@TiberiumPY Thanks! Did you forget a link or a list of versions ?

**Comment by TiberiumPY** [comment]
@SylvainDe ah, yes!
https://paste.pound-python.org/show/s9ZtjUcXvaLSoigIFYhf/

**Comment by SylvainDe** [comment]
@TiberiumPY Wahoo, thank you again! I'll try to pick a relevant subset and put this in my travis.yml file.

**Comment by SylvainDe** [comment]
Also I've just realised the reason why the script maybe failing: a different test used to set a particular recursion limit in order to reach the limit easily. I would probably make sense to save the original value and reset it.

**Comment by SylvainDe** [comment]
@TiberiumPY I have the feeling I have solved the issue and thanks to your help gone a bit further so thanks again for the suggestions!

**Comment by SylvainDe** [comment]
Note to myself : this issue came back for no obvious reason.

```
https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/258923496 Job #807.13
$ python --version
Python 2.7.10 (7e8df3df9641, Jun 14 2016, 13:58:02)
[PyPy 5.3.1 with GCC 4.8.2]
OK

====================================================================================

https://travis-ci.org/SylvainDe/DidYouMean-Python/jobs/259141829 Job #808.13
$ python --version
Python 2.7.10 (7e8df3df9641, Jun 14 2016, 13:58:02)
[PyPy 5.3.1 with GCC 4.8.2]
```

It was fixed with an adaptation of the original fix : https://github.com/SylvainDe/DidYouMean-Python/commit/78c0ba07585daa52b87ccfbdd5ead2732efa11a7 .
